spring:
  application:
    name: application-dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_PATH}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 1800000 #30분

  refresh:
    expiration: 604800000 #7일

#logging:
#  discord:
#    webhook-url: ${DISCORD_WEBHOOK_URL}
#  config: classpath:logback-spring.xml

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_ACCESS_PASSWORD}