spring:
  application:
    name: application-local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_PATH}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 1800000 #30분

  refresh:
    expiration: 604800000 #7일

#logging:
#  discord:
#    webhook-uri: ${DISCORD_WEBHOOK_URI}
#  config: classpath:logback-test.xml

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_ACCESS_PASSWORD}