spring:
  profiles:
    active: local # dev: 개발 서버, local: 로컬 개발

  output:
    ansi:
      enabled: always #콘솔 색상

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          servlet:
            handler:
              SimpleUrlHandlerMapping: WARN
      springframework.security: DEBUG

    com:
      fasterxml.jackson: DEBUG